### ISSUE TITLE
[FEATURE] Swipe from left to right to open the Menu

### ISSUE THREAD

**Issue by diegoveloper** [diegoveloper/flutter_side_menu_animation#2]
It would be great to have an optional parameter to allow us to use a gesture(swipe), from left to right to display the Menu.
Right now the only way is press the button from our `AppBar`.

**Comment by AlejandroRodriguez05** [comment]
Hello good Diego make a change in the package that is being that you can put the menu position (left or right).

**Comment by diegoveloper** [comment]
Thanks @br-programmer
