### ISSUE TITLE
[FEATURE] Add a Position menu parameter

### ISSUE THREAD

**Issue by AlejandroRodriguez05** [diegoveloper/flutter_side_menu_animation#4]
Hello good Diego make a change in the package that is being that you can put the menu position (left or right).

**Comment by diegoveloper** [comment]
Sure, do you want to implement that feature?

**Comment by AlejandroRodriguez05** [comment]
Yes, I'm sure

**Comment by diegoveloper** [comment]
ok, sounds good. Don't forget to execute `dartfmt . -w` before you send the Pull request.

**Comment by AlejandroRodriguez05** [comment]
thank you, yes, I did perform the dartfmt before making the pr

**Comment by diegoveloper** [comment]
Fixed on #5
