### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Ascenio** [diegoveloper/flutter_side_menu_animation#6]
As it stands the package has some significant level of UI logic, if that makes sense. How could we test if the page is swapped once menu item get tapped, but also not change page if the X option is tapped?

You could (or couldn't? Idk) test if the menu both opens and closes from top to bottom correctly? That's trickier because it isn't just checking if a widget is on the screen, it requires some more thought because you have to _follow_ the animation.

I think tests are a good idea because it should generate some good content for the yt channel, but also because tests are a must nowadays.

**Comment by diegoveloper** [comment]
Hey there, I added some widget tests , you can check the `main` branch and also I made a video about that if you want to learn => https://www.youtube.com/watch?v=L6hUBeLJH0g  , If you don't know spanish you can activate the english subtitles , just check the video description. 
And of course you are invited to contribute with more widget tests.

**Comment by Ascenio** [comment]
Oh nice. I'm definitely going to take a look. Thank you ;)
